---
title: "ChIPpeakAnno: Human"
author: "RuiLi"
date: "06/09/2019"
output: html_document
---

## Update database
```{r, include=FALSE}
# Install
# if (!requireNamespace("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# 
# BiocManager::install("org.Hs.eg.db")
# BiocManager::install("reactome.db")
# BiocManager::install("KEGG.db")

# Update
BiocManager::install()
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("ChIPpeakAnno")
library("AnnotationDbi") 
library("org.Hs.eg.db")
library("org.Mm.eg.db")
library('reactome.db')
library("KEGG.db")
library(WriteXLS)
```

## print versions
```{r}
sessionInfo()
```

# Communications:
- Enrichment results for Significant DEG

# Notes:
- first written for Caitlin
- 190609: update databases; use gene_symbol for GENCODE anno
- 190609: added mouse support
- 190611: print out summaries
- 190805: LFC -> LFC_shrinked

# Read
```{r}
df <- readxl::read_xlsx( '../DESeq2/Fasudil_vs_DMSO.deseq2.sig.FDR.0.05.LFC.1.xlsx', na = '-')
df <- data.frame(df)  #important

df$Gene <-  gsub("\\..+$", "", df$Gene)  # remove extra part


colnames(df)
dim(df)
head(df)
```

# Parameters
```{r}
# FOR DEG
max_padj = 0.05
min_lfc = 1

# FOR Enrichment
max_BH = 0.1
org_eg_eb <- "org.Hs.eg.db"
```


# Filter Sig DEG
```{r}
print("Filtering Sig DEG:")
small_fdr <- df$padj<max_padj
small_fdr[is.na(small_fdr)] <- FALSE
paste('FDR <', max_padj, ':', sum(small_fdr))

large_lfc <- abs(df$log2FoldChange_shrinked) > min_lfc
large_lfc[is.na(large_lfc)] <- FALSE
paste('|log2FoldChange| >', min_lfc , ':', sum(large_lfc))

both <- small_fdr & large_lfc
paste('both:', sum(both))
sum(is.na(both))
```


## Out sig excel
```{r}
df_sig <- df[both, ]
# WriteXLS(x = df_sig, 
#          ExcelFileName = 'significant.FDR0.05.FC1.5.xlsx', row.names = F, SheetNames = 'sheet1', na = '-')
keys <- df[both, "Name"]
```

## ChIPpeakAnno::getEnrichedGO
```{r}
paste(org_eg_eb)

enriched.GO.both.condense <- getEnrichedGO(
    keys, 
    orgAnn=org_eg_eb, 
    feature_id_type = "gene_symbol", 
    maxP=max_BH,
    minGOterm=10,
    multiAdjMethod= "BH", 
    condense = T  # all genes in one line
)

```

<!-- # Reactome (Only path id, no path name) -->
<!-- ```{r} -->
<!-- enriched.PATH.both <- getEnrichedPATH( -->
<!--     keys, -->
<!--     orgAnn="org.Hs.eg.db", -->
<!--     pathAnn = "reactome.db", -->
<!--     feature_id_type = "gene_symbol", -->
<!--     maxP=max_BH, -->
<!--     minPATHterm=10, -->
<!--     multiAdjMethod= "BH" -->
<!-- ) -->

<!-- head(enriched.PATH.both) -->


<!-- enriched.PATH.both.condense <- condenseMatrixByColnames(as.matrix(enriched.PATH.both), "path.id") -->
<!-- ``` -->


# KEGG
```{r}
kegg <- getEnrichedPATH(
    keys, 
    orgAnn=org_eg_eb, 
    pathAnn = "KEGG.db",
    feature_id_type = "gene_symbol", 
    maxP=max_BH,
    minPATHterm=10,
    multiAdjMethod= "BH"
)

kegg <- condenseMatrixByColnames(as.matrix(kegg), "path.id")

head(kegg)

```

## Output
```{r}
library(WriteXLS)

paste("enriched.GO.both.condense$bp", dim(enriched.GO.both.condense$bp)[1])
WriteXLS(x = enriched.GO.both.condense$bp,
        ExcelFileName = paste('GO_biological_process', max_BH, 'xlsx', sep = '.'), 
        row.names = F, SheetNames = 'sheet1', na = '-')

paste("enriched.GO.both.condense$cc", dim(enriched.GO.both.condense$cc)[1])
WriteXLS(x = enriched.GO.both.condense$cc,
        ExcelFileName = paste('GO_cellular_component', max_BH, 'xlsx', sep = '.'),
        row.names = F, SheetNames = 'sheet1', na = '-')

paste("enriched.GO.both.condense$mf", dim(enriched.GO.both.condense$mf)[1])
WriteXLS(x = enriched.GO.both.condense$mf,
        ExcelFileName = paste('GO_mulecular_function', max_BH, 'xlsx', sep = '.'),
        row.names = F, SheetNames = 'sheet1', na = '-')

# WriteXLS(x = enriched.PATH.both.condense,
#         ExcelFileName = 'reactome.db.FDR0.05.FC1.5.xlsx', row.names = F, SheetNames = 'sheet1', na = '-')

paste("kegg", dim(kegg)[1])
WriteXLS(x = kegg,
        ExcelFileName = paste('KEGG', max_BH, 'xlsx', sep = '.'),
        row.names = F, SheetNames = 'sheet1', na = '-')

```

