---
title: "Filter Significant Genes"
author: "RuiLi"
date: "10/05/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(WriteXLS)
require(gdata)  #best reading xls
```

## Params
```{r}
thr_p <- 0.01
thr_lfc <- 1
```

## Read Data
```{r}
df = read.xls ("KD_vs_NS.deseq.anno.xls", 
               sheet = 1, header = TRUE, na.strings = '-')

row.names(df) <- df[,1]
df <- df[, -1]
colnames(df)

# remove NA from padj
sum(is.na(df$padj))
df[is.na(df$padj), 'padj'] <- 1  
sum(is.na(df$padj))
```


## Filter
```{r one}
name<-""
outname<-"KD_vs_NS"

name_padj<-paste('padj', name, sep='') 
name_fc<-paste('log2FoldChange', name, sep='') 

small_p <- df[,name_padj] < thr_p
large_lfc <- abs(df[, name_fc]) > thr_lfc

df_fdr <- df[small_p, ]
num_fdr <- dim(df_fdr)[1]
paste(name, 'small_fdr:', num_fdr)

df_lfc <- df[large_lfc, ]
num_lfc <- dim(df_lfc)[1]
paste(name, 'large_lfc:', num_lfc)

df_both <- df[(small_p & large_lfc) , ]
num_both <- dim(df_both)[1]
paste(name, 'both:', num_both)

WriteXLS(x = df_fdr, 
         ExcelFileName = paste(outname, ".FDR", thr_p, ".sig.xls", sep = ""), 
         row.names = T, SheetNames = 'sheet1', na = '-')

WriteXLS(x = df_both, 
         ExcelFileName = paste(outname, ".FDR", thr_p, ".LFC", thr_lfc, ".sig.xls", sep = ""), 
         row.names = T, SheetNames = 'sheet1', na = "-")
```

