---
title: "DESeq2_2F_Batch(lfcShink, ashr, contrast)"
author: "RuiLi"
date: "07/26/2018"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# source("https://bioconductor.org/biocLite.R")
# biocLite("DESeq2")
# biocLite("apeglm")
library(DESeq2)
# library('apeglm')

thresh_p <- 0.1
thresh_FC <- 1

volcanoplot <- function (res, lfcthresh=2, sigthresh=thresh_p, 
                         main=paste("Volcano Plot", name, sep='\n'), 
                         legendpos="topright", labelsig=FALSE, textcx=1, ...) {
  with(res, plot(log2FoldChange, -log10(pvalue), pch=20, main=main, ...))
  with(subset(res, padj<sigthresh ), points(log2FoldChange, -log10(pvalue), pch=20, col="orange", ...))
  with(subset(res, abs(log2FoldChange)>lfcthresh), points(log2FoldChange, -log10(pvalue), pch=20, col="green", ...))
  with(subset(res, padj<sigthresh & abs(log2FoldChange)>lfcthresh), points(log2FoldChange, -log10(pvalue), pch=20, col="red", ...))
  if (labelsig) {
    require(calibrate)
    with(subset(res, padj<sigthresh & abs(log2FoldChange)>lfcthresh), textxy(log2FoldChange, -log10(pvalue), labs=Gene, cex=textcx, ...))
  }
  legend(legendpos, xjust=1, yjust=0.5, 
         legend=c(paste("FDR<",sigthresh,sep=""), 
                  paste("|LogFC|>",lfcthresh,sep=""), 
                  "both"), pch=20,
         col=c("orange","green","red"))
}

maplot <- function (res, thresh=thresh_p, labelsig=FALSE, textcx=1, ...) {
  with(res, plot(baseMean, log2FoldChange, pch=20, cex=.5, log="x", ...))
  with(subset(res, padj<thresh_p), points(baseMean, log2FoldChange, col="red", pch=20, cex=1.5))
  if (labelsig) {
    require(calibrate)
    with(subset(res, padj<thresh_p), textxy(baseMean, log2FoldChange, labs=Gene, cex=textcx, col=2))
  }
}

```

## Read Data
```{r}
df <- read.table('../counts.gene_id.txt', sep="\t",
                 header=TRUE, row.names=1)

cts <- df[,6:ncol(df)]

colnames(cts) <- gsub("\\.Aligned.out.bam$", "", colnames(cts))
colnames(cts) <- gsub("...star.", "", colnames(cts))
colnames(cts) <- gsub("C241", "C261", colnames(cts)) # fix C241, C261 misname

cts <- cts[, c(1:8, 10:11, 9, 12)]  # fix C241, C261 misname

cts <- cts[, c(1,5,9,
               2,6,10,
               3,7,11,
               4,8,12)]  # fix order

cts <- as.matrix(cts)
dim(cts)
head(cts)
```

```{r}
## Filter Based on Expression
exp_idx <- rowSums(cts) >= 1  # default 10
cts <- cts[exp_idx, ]
dim(cts)
head(cts)
```


## DESeq Experiment Design
```{r}
mut1 <- factor(rep(c('yhp1','WT','yhp1','WT'), each=3))
mut2 <- factor(rep(c('WT','yox1','yox1','WT'), each=3))
batch <- factor(rep(c('A','B','C'), 4))
coldata <- data.frame(row.names=colnames(cts), mut1, mut2, batch)
coldata
```


## Create dds obj
```{r}
dds <- DESeqDataSetFromMatrix(countData = cts, 
                              colData = coldata, 
                              design = ~ mut1 + mut2 + mut1:mut2 + batch )  # converted to alph-order

dds
dds <-DESeq(dds)
resultsNames(dds)
```


```{r}
## Data transformation (for PCA plot etc.)
vsd <- vst(dds, blind=FALSE)

rld <- rlog(dds, blind=FALSE)

counts <- counts(dds, normalized=0)
logCounts <- log10(counts +1 )

normed <- counts(dds, normalized=1)
logNormed <- log10(normed+1)
hist(logNormed)

```


```{r}
## Commom Plots
plotDispEsts(dds, main="Dispersion plot")

plotPCA(vsd, intgroup=c("batch"), )
plotPCA(vsd, intgroup=c("mut1", "mut2"))

library("RColorBrewer")
library('pheatmap')
library("PoiClaClu")
poisd <- PoissonDistance(t(counts(dds)))
samplePoisDistMatrix <- as.matrix( poisd$dd ) 
rownames(samplePoisDistMatrix) <- paste( vsd$mut1, vsd$mut2, vsd$batch, sep="-" ) 
colnames(samplePoisDistMatrix) <- NULL 
pheatmap(samplePoisDistMatrix,
         clustering_distance_rows=poisd$dd,
         clustering_distance_cols=poisd$dd,
         col=colors)
```

```{r}

```

```{r}
res1 <- lfcShrink(dds, coef="mut1_yhp1_vs_WT", type='ashr')
name1 <- 'yhp1_vs_WT'
summary(res1, alpha=thresh_p)
table(res1$padj<thresh_p)
```

```{r}
res2 <- lfcShrink(dds, coef="mut2_yox1_vs_WT", type='ashr')
name2 <- 'yox1_vs_WT'
summary(res2, alpha=thresh_p)
table(res2$padj<thresh_p)
```
```{r}
res3 <- lfcShrink(dds, contrast = list(c('mut1_yhp1_vs_WT', 'mut2_yox1_vs_WT', 'mut1yhp1.mut2yox1')), type='ashr')
name3 <- 'double_vs_WT'
summary(res3, alpha=thresh_p)
table(res3$padj<thresh_p)
```

```{r}
res4 <- lfcShrink(dds, contrast = list(c('mut2_yox1_vs_WT', 'mut1yhp1.mut2yox1')), type='ashr')
name4 <- 'double_vs_yhp1'
summary(res4, alpha=thresh_p)
table(res4$padj<thresh_p)
```

```{r}
res5 <- lfcShrink(dds, contrast = list(c('mut1_yhp1_vs_WT', 'mut1yhp1.mut2yox1')), type='ashr')
name5 <- 'double_vs_yox1'
summary(res5, alpha=thresh_p)
table(res5$padj<thresh_p)
```

```{r}
res6 <- lfcShrink(dds, coef = "mut1yhp1.mut2yox1", type='ashr')
name6 <- 'interaction_yhp1_and_yox1'
summary(res6, alpha=thresh_p)
table(res6$padj<thresh_p)
```

## RES1
```{r}
res <- res1
name <- name1
num_sig <- as.integer(table(res$padj<thresh_p)[2])
paste(name, num_sig)

## Order by adjusted p-value
resOrdered <- res[order(res$padj), ]
## Merge with normalized count data
resdata <- merge(as.data.frame(resOrdered), as.data.frame(counts(dds, normalized=TRUE)), 
                 by="row.names", sort=FALSE)
names(resdata)[1] <- "Gene"
head(resdata)
## Write results
write.csv(resdata, row.names = FALSE, 
          file=paste(name, 'deseq.csv', sep = '.'))

## Contrast Specific Plots
library("pheatmap")
select <- order(res$pvalue)[1:20]
df_anno <- as.data.frame(colData(dds)[,c("mut1", "mut2","batch")])
pheatmap(logNormed[select,], cluster_rows=0, show_rownames=1,
         cluster_cols=0, annotation_col=df_anno, 
         main = paste(paste(name, "(top 20 by pvalue)"), 
                      paste('total', num_sig, "DEG"), 
                      sep="\n") 
         )

## Examine plot of p-values
hist(res$pvalue, breaks=50, col="grey", 
     main = paste('Histogram of p-values (un-adjusted)', name, sep = "\n"), 
     xlab = 'pvalues', ylab = 'Frequency')

hist(res$padj, breaks=50, col="grey", 
     main = paste('Histogram of p-values (adjusted)', name, sep = "\n"), 
     xlab = 'pvalues', ylab = 'Frequency')

## MA plot
maplot(resdata, main=paste("MAplot", name, sep="\n"))


## Volcano plot with "significant" genes labeled
volcanoplot(resdata, lfcthresh=thresh_FC, sigthresh=thresh_p, textcx=.8, xlim=c(-2.3, 2))
```


## RES2
```{r}
res <- res2
name <- name2
num_sig <- as.integer(table(res$padj<thresh_p)[2])
paste(name, num_sig)

## Order by adjusted p-value
resOrdered <- res[order(res$padj), ]
## Merge with normalized count data
resdata <- merge(as.data.frame(resOrdered), as.data.frame(counts(dds, normalized=TRUE)), 
                 by="row.names", sort=FALSE)
names(resdata)[1] <- "Gene"
head(resdata)
## Write results
write.csv(resdata, row.names = FALSE, 
          file=paste(name, 'deseq.csv', sep = '.'))

## Contrast Specific Plots
library("pheatmap")
select <- order(res$pvalue)[1:20]
df_anno <- as.data.frame(colData(dds)[,c("mut1", "mut2","batch")])
pheatmap(logNormed[select,], cluster_rows=0, show_rownames=1,
         cluster_cols=0, annotation_col=df_anno, 
         main = paste(paste(name, "(top 20 by pvalue)"), 
                      paste('total', num_sig, "DEG"), 
                      sep="\n") 
         )

## Examine plot of p-values
hist(res$pvalue, breaks=50, col="grey", 
     main = paste('Histogram of p-values (un-adjusted)', name, sep = "\n"), 
     xlab = 'pvalues', ylab = 'Frequency')

hist(res$padj, breaks=50, col="grey", 
     main = paste('Histogram of p-values (adjusted)', name, sep = "\n"), 
     xlab = 'pvalues', ylab = 'Frequency')

## MA plot
maplot(resdata, main=paste("MAplot", name, sep="\n"))


## Volcano plot with "significant" genes labeled
volcanoplot(resdata, lfcthresh=thresh_FC, sigthresh=thresh_p, textcx=.8, xlim=c(-2.3, 2))
```


## RES3
```{r}
res <- res3
name <- name3
num_sig <- as.integer(table(res$padj<thresh_p)[2])
paste(name, num_sig)

## Order by adjusted p-value
resOrdered <- res[order(res$padj), ]
## Merge with normalized count data
resdata <- merge(as.data.frame(resOrdered), as.data.frame(counts(dds, normalized=TRUE)), 
                 by="row.names", sort=FALSE)
names(resdata)[1] <- "Gene"
head(resdata)
## Write results
write.csv(resdata, row.names = FALSE, 
          file=paste(name, 'deseq.csv', sep = '.'))

## Contrast Specific Plots
library("pheatmap")
select <- order(res$pvalue)[1:20]
df_anno <- as.data.frame(colData(dds)[,c("mut1", "mut2","batch")])
pheatmap(logNormed[select,], cluster_rows=0, show_rownames=1,
         cluster_cols=0, annotation_col=df_anno, 
         main = paste(paste(name, "(top 20 by pvalue)"), 
                      paste('total', num_sig, "DEG"), 
                      sep="\n") 
         )

## Examine plot of p-values
hist(res$pvalue, breaks=50, col="grey", 
     main = paste('Histogram of p-values (un-adjusted)', name, sep = "\n"), 
     xlab = 'pvalues', ylab = 'Frequency')

hist(res$padj, breaks=50, col="grey", 
     main = paste('Histogram of p-values (adjusted)', name, sep = "\n"), 
     xlab = 'pvalues', ylab = 'Frequency')

## MA plot
maplot(resdata, main=paste("MAplot", name, sep="\n"))


## Volcano plot with "significant" genes labeled
volcanoplot(resdata, lfcthresh=thresh_FC, sigthresh=thresh_p, textcx=.8, xlim=c(-2.3, 2))
```


## RES4
```{r}
res <- res4
name <- name4
num_sig <- as.integer(table(res$padj<thresh_p)[2])
paste(name, num_sig)

## Order by adjusted p-value
resOrdered <- res[order(res$padj), ]
## Merge with normalized count data
resdata <- merge(as.data.frame(resOrdered), as.data.frame(counts(dds, normalized=TRUE)), 
                 by="row.names", sort=FALSE)
names(resdata)[1] <- "Gene"
head(resdata)
## Write results
write.csv(resdata, row.names = FALSE, 
          file=paste(name, 'deseq.csv', sep = '.'))

## Contrast Specific Plots
library("pheatmap")
select <- order(res$pvalue)[1:20]
df_anno <- as.data.frame(colData(dds)[,c("mut1", "mut2","batch")])
pheatmap(logNormed[select,], cluster_rows=0, show_rownames=1,
         cluster_cols=0, annotation_col=df_anno, 
         main = paste(paste(name, "(top 20 by pvalue)"), 
                      paste('total', num_sig, "DEG"), 
                      sep="\n") 
         )

## Examine plot of p-values
hist(res$pvalue, breaks=50, col="grey", 
     main = paste('Histogram of p-values (un-adjusted)', name, sep = "\n"), 
     xlab = 'pvalues', ylab = 'Frequency')

hist(res$padj, breaks=50, col="grey", 
     main = paste('Histogram of p-values (adjusted)', name, sep = "\n"), 
     xlab = 'pvalues', ylab = 'Frequency')

## MA plot
maplot(resdata, main=paste("MAplot", name, sep="\n"))


## Volcano plot with "significant" genes labeled
volcanoplot(resdata, lfcthresh=thresh_FC, sigthresh=thresh_p, textcx=.8, xlim=c(-2.3, 2))
```


## RES5
```{r}
res <- res5
name <- name5
num_sig <- as.integer(table(res$padj<thresh_p)[2])
paste(name, num_sig)

## Order by adjusted p-value
resOrdered <- res[order(res$padj), ]
## Merge with normalized count data
resdata <- merge(as.data.frame(resOrdered), as.data.frame(counts(dds, normalized=TRUE)), 
                 by="row.names", sort=FALSE)
names(resdata)[1] <- "Gene"
head(resdata)
## Write results
write.csv(resdata, row.names = FALSE, 
          file=paste(name, 'deseq.csv', sep = '.'))

## Contrast Specific Plots
library("pheatmap")
select <- order(res$pvalue)[1:20]
df_anno <- as.data.frame(colData(dds)[,c("mut1", "mut2","batch")])
pheatmap(logNormed[select,], cluster_rows=0, show_rownames=1,
         cluster_cols=0, annotation_col=df_anno, 
         main = paste(paste(name, "(top 20 by pvalue)"), 
                      paste('total', num_sig, "DEG"), 
                      sep="\n") 
         )

## Examine plot of p-values
hist(res$pvalue, breaks=50, col="grey", 
     main = paste('Histogram of p-values (un-adjusted)', name, sep = "\n"), 
     xlab = 'pvalues', ylab = 'Frequency')

hist(res$padj, breaks=50, col="grey", 
     main = paste('Histogram of p-values (adjusted)', name, sep = "\n"), 
     xlab = 'pvalues', ylab = 'Frequency')

## MA plot
maplot(resdata, main=paste("MAplot", name, sep="\n"))


## Volcano plot with "significant" genes labeled
volcanoplot(resdata, lfcthresh=thresh_FC, sigthresh=thresh_p, textcx=.8, xlim=c(-2.3, 2))
```


## RES6
```{r}
res <- res6
name <- name6
num_sig <- as.integer(table(res$padj<thresh_p)[2])
paste(name, num_sig)

## Order by adjusted p-value
resOrdered <- res[order(res$padj), ]
## Merge with normalized count data
resdata <- merge(as.data.frame(resOrdered), as.data.frame(counts(dds, normalized=TRUE)), 
                 by="row.names", sort=FALSE)
names(resdata)[1] <- "Gene"
head(resdata)
## Write results
write.csv(resdata, row.names = FALSE, 
          file=paste(name, 'deseq.csv', sep = '.'))

## Contrast Specific Plots
library("pheatmap")
select <- order(res$pvalue)[1:20]
df_anno <- as.data.frame(colData(dds)[,c("mut1", "mut2","batch")])
pheatmap(logNormed[select,], cluster_rows=0, show_rownames=1,
         cluster_cols=0, annotation_col=df_anno, 
         main = paste(paste(name, "(top 20 by pvalue)"), 
                      paste('total', num_sig, "DEG"), 
                      sep="\n") 
         )

## Examine plot of p-values
hist(res$pvalue, breaks=50, col="grey", 
     main = paste('Histogram of p-values (un-adjusted)', name, sep = "\n"), 
     xlab = 'pvalues', ylab = 'Frequency')

hist(res$padj, breaks=50, col="grey", 
     main = paste('Histogram of p-values (adjusted)', name, sep = "\n"), 
     xlab = 'pvalues', ylab = 'Frequency')

## MA plot
maplot(resdata, main=paste("MAplot", name, sep="\n"))


## Volcano plot with "significant" genes labeled
volcanoplot(resdata, lfcthresh=thresh_FC, sigthresh=thresh_p, textcx=.8, xlim=c(-2.3, 2))
```