---
title: "Filter Significant Genes"
author: "RuiLi"
date: "9/06/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("pheatmap")
library(WriteXLS)
```

## Params
```{r}
thr_p <- 0.05
thr_fc <- 1.5
```


## Read Data
```{r}
require(gdata)  #best
df = read.xls ("merged.deseq.ann.rui.xls", sheet = 1, header = TRUE)

row.names(df) <- df[,1]
df <- df[, -1]
colnames(df)

# select expression columns
df_ <- df[, c(1:8)]
colnames(df_)

# remove NA from padj
sum(is.na(df$padj.WT.TRT.UNT))
df[is.na(df$padj.WT.TRT.UNT), 'padj.WT.TRT.UNT'] <- 1  
sum(is.na(df$padj.WT.TRT.UNT))

sum(is.na(df$padj.MUT.TRT.UNT))
df[is.na(df$padj.MUT.TRT.UNT), 'padj.MUT.TRT.UNT'] <- 1  
sum(is.na(df$padj.MUT.TRT.UNT))

sum(is.na(df$padj.TRT.MUT_vs_WT))
df[is.na(df$padj.TRT.MUT_vs_WT), 'padj.TRT.MUT_vs_WT'] <- 1  
sum(is.na(df$padj.TRT.MUT_vs_WT))

sum(is.na(df$padj.UNT.MUT_vs_WT))
df[is.na(df$padj.UNT.MUT_vs_WT), 'padj.UNT.MUT_vs_WT'] <- 1  
sum(is.na(df$padj.UNT.MUT_vs_WT))
```


## 1 for WT.TRT.UNT
```{r one}
name<-"WT.TRT.UNT"
outname<-"WT(TRT_vs_UNT)"

name_padj<-paste('padj', name, sep='.') 
name_fc<-paste('FoldChange', name, sep='.') 

small_p <- df[,name_padj] < thr_p
large_fc <- df[, name_fc] > thr_fc | df[, name_fc] < 1/thr_fc

df_fdr <- df[small_p, ]
num_fdr <- dim(df_fdr)[1]
paste(name, 'small_fdr:', num_fdr)

df_both <- df[(small_p & large_fc) , ]
num_both <- dim(df_both)[1]
paste(name, 'both:', num_both)

# select columns for output
out_idx <- c(grep (name, names(df)),  # DE stats
             grep ('gene_name', names(df)), grep ('GO', names(df)), grep ('description', names(df)), # Anno
             1:8 # Expression
             ) 
out_fdr <- df_fdr[, out_idx]
out_both <- df_both[, out_idx]

WriteXLS(x = out_fdr, 
         ExcelFileName = paste(outname, ".FDR", thr_p, ".sig.xls", sep = ""), 
         row.names = T, SheetNames = 'sheet1')

WriteXLS(x = out_both, 
         ExcelFileName = paste(outname, ".FDR", thr_p, ".FC", thr_fc, ".sig.xls", sep = ""), 
         row.names = T, SheetNames = 'sheet1')
```


## 2 for MUT.TRT.UNT
```{r two}
name<-"MUT.TRT.UNT"
outname<-"MUT(TRT_vs_UNT)"

name_padj<-paste('padj', name, sep='.') 
name_fc<-paste('FoldChange', name, sep='.') 

small_p <- df[,name_padj] < thr_p
large_fc <- df[, name_fc] > thr_fc | df[, name_fc] < 1/thr_fc

df_fdr <- df[small_p, ]
num_fdr <- dim(df_fdr)[1]
paste(name, 'small_fdr:', num_fdr)

df_both <- df[(small_p & large_fc) , ]
num_both <- dim(df_both)[1]
paste(name, 'both:', num_both)

# select columns for output
out_idx <- c(grep (name, names(df)),  # DE stats
             grep ('gene_name', names(df)), grep ('GO', names(df)), grep ('description', names(df)), # Anno
             1:8 # Expression
             ) 
out_fdr <- df_fdr[, out_idx]
out_both <- df_both[, out_idx]

WriteXLS(x = out_fdr, 
         ExcelFileName = paste(outname, ".FDR", thr_p, ".sig.xls", sep = ""), 
         row.names = T, SheetNames = 'sheet1')

WriteXLS(x = out_both, 
         ExcelFileName = paste(outname, ".FDR", thr_p, ".FC", thr_fc, ".sig.xls", sep = ""), 
         row.names = T, SheetNames = 'sheet1')
```

## 3 for MUT.TRT.UNT
```{r three}
name<-"TRT.MUT_vs_WT"
outname<-"TRT(MUT_vs_WT)"

name_padj<-paste('padj', name, sep='.') 
name_fc<-paste('FoldChange', name, sep='.') 

small_p <- df[,name_padj] < thr_p
large_fc <- df[, name_fc] > thr_fc | df[, name_fc] < 1/thr_fc

df_fdr <- df[small_p, ]
num_fdr <- dim(df_fdr)[1]
paste(name, 'small_fdr:', num_fdr)

df_both <- df[(small_p & large_fc) , ]
num_both <- dim(df_both)[1]
paste(name, 'both:', num_both)

# select columns for output
out_idx <- c(grep (name, names(df)),  # DE stats
             grep ('gene_name', names(df)), grep ('GO', names(df)), grep ('description', names(df)), # Anno
             1:8 # Expression
             ) 
out_fdr <- df_fdr[, out_idx]
out_both <- df_both[, out_idx]

WriteXLS(x = out_fdr, 
         ExcelFileName = paste(outname, ".FDR", thr_p, ".sig.xls", sep = ""), 
         row.names = T, SheetNames = 'sheet1')

WriteXLS(x = out_both, 
         ExcelFileName = paste(outname, ".FDR", thr_p, ".FC", thr_fc, ".sig.xls", sep = ""), 
         row.names = T, SheetNames = 'sheet1')
```

## 4 for WT.TRT.UNT
```{r four}
name<-"UNT.MUT_vs_WT"
outname<-"UNT(MUT_vs_WT)"

name_padj<-paste('padj', name, sep='.') 
name_fc<-paste('FoldChange', name, sep='.') 

small_p <- df[,name_padj] < thr_p
large_fc <- df[, name_fc] > thr_fc | df[, name_fc] < 1/thr_fc

df_fdr <- df[small_p, ]
num_fdr <- dim(df_fdr)[1]
paste(name, 'small_fdr:', num_fdr)

df_both <- df[(small_p & large_fc) , ]
num_both <- dim(df_both)[1]
paste(name, 'both:', num_both)

# select columns for output
out_idx <- c(grep (name, names(df)),  # DE stats
             grep ('gene_name', names(df)), grep ('GO', names(df)), grep ('description', names(df)), # Anno
             1:8 # Expression
             ) 
out_fdr <- df_fdr[, out_idx]
out_both <- df_both[, out_idx]

WriteXLS(x = out_fdr, 
         ExcelFileName = paste(outname, ".FDR", thr_p, ".sig.xls", sep = ""), 
         row.names = T, SheetNames = 'sheet1')

WriteXLS(x = out_both, 
         ExcelFileName = paste(outname, ".FDR", thr_p, ".FC", thr_fc, ".sig.xls", sep = ""), 
         row.names = T, SheetNames = 'sheet1')
```

