---
title: "Heatmap for DEG: Dr. Mao, Lined Labels"
author: "RuiLi"
date: "09/14/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("pheatmap")
```

# Read Data
```{r echo=FALSE}
# require(gdata)  #best
# df = read.xls ("../MUT_vs_WT.deseq.ann.rui.xls", sheet = 1, header = TRUE)
# row.names(df) <- df[,1]
# df <- df[, -1]
# saveRDS(df, "df.rds")
df <- readRDS('df.rds')

colnames(df)
```

## Filter Data
```{r}
name <- 'MUT_vs_WT'
thr_p <- 0.05
thr_fc <- 1.25
```

```{r echo=FALSE}
# remove NA from padj
df[is.na(df$padj.FDR.), 'padj.FDR.'] <- 1  

# remove NA from FoldChange
df[is.na(df$FoldChange), 'FoldChange'] <- 0 

# select significant genes
small_p <- df$padj.FDR.<thr_p
large_fc <- df$FoldChange > thr_fc | df$FoldChange < 1/thr_fc
sig <- small_p & large_fc

df_sig <- df[sig, ]
df_sig <- df_sig[order(df_sig$FoldChange, decreasing = F), ]
values_sig <- df_sig[, c(4:7)]
logNormed_sig <- log10(values_sig + 1)  # log transformation

# write.csv(df_sig, "fc1.25.fdr0.05.sig.csv")

num_sig <- dim(df_sig)[1]
paste(num_sig, "significant genes")
```


## Heatmap for DEG 
```{r heatmap fig, fig.height = 6, fig.width = 3.5, fofig.align = "center", echo=FALSE}
# source("https://bioconductor.org/biocLite.R")
# biocLite("ComplexHeatmap")
library(ComplexHeatmap)
library(circlize)

mat <- logNormed_sig
row.names(mat) <- df_sig$gene_name
max_exp <- max(logNormed_sig)

labels <- as.character(df_sig$gene_name)
# markers <- c("Ctgf", "Cyr61", 'Ankrd1', 'Axin2')  # MEF
markers <- c('CTGF', 'Cyr61', 'ANKRD1', 'Ajuba', 'Amot', 'Lgr5', 'Axin2', 
             'CD44', 'EphB2', 'EphB3', 'Atoh1',  'GFi1', 'SPDEF', 'NGN3', 
             'NKX2-2', 'Olfm4', 'Smoc2')  # INTESTINE, NGN3 not found (alias tested)
marker_idx <- match(tolower(markers), tolower(labels))
labels[marker_idx]

header = data.frame(type = c('MUT', 'MUT', 'WT', 'WT'))

ha = HeatmapAnnotation(df = header,  
                       col = list(type = c("MUT" =  "red", "WT" = "blue")))
Heatmap(mat, 
        column_title = 'Heatmap',
        row_title = 'genes sorted by FC',
        name = 'Exp',
        cluster_rows = F,
        show_row_names = F,
        show_column_names = F,
        show_row_dend = T, 
        show_column_dend = F,
        top_annotation = ha, 
        col = colorRamp2(c(0, max_exp/2, max_exp), c("blue", "white", "red")), 
        fontsize(4)
        ) + 
  rowAnnotation(link = row_anno_link(at = marker_idx, labels = markers),
                width = unit(5, "mm") + 
                  max_text_width(markers))

```

