---
title: "Merge DESeq Tables"
author: "RuiLi"
date: "02/11/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## read csv 
## stats
df1 = read.csv("../1.deseq_csv/1.Tris13_vs_WT.deseq.csv", header = TRUE)[1:6]
colnames(df1)[3:6] = paste('1', colnames(df1)[3:6], sep='.')

df2 = read.csv("../1.deseq_csv/2.Tris18_vs_WT.deseq.csv",  header = TRUE)[1:6]
colnames(df2)[3:6] = paste('2', colnames(df2)[3:6], sep='.')

df3 = read.csv("../1.deseq_csv/3.Tris21_vs_WT.deseq.csv",  header = TRUE)[1:6]
colnames(df3)[3:6] = paste('3', colnames(df3)[3:6], sep='.')

df4 = read.csv("../1.deseq_csv/4.Tris13_F_vs_WT_F.deseq.csv",  header = TRUE)[1:6]
colnames(df4)[3:6] = paste('4', colnames(df4)[3:6], sep='.')

df5 = read.csv("../1.deseq_csv/5.Tris18_F_vs_WT_F.deseq.csv",  header = TRUE)[1:6]
colnames(df5)[3:6] = paste('5', colnames(df5)[3:6], sep='.')

df6 = read.csv("../1.deseq_csv/6.Tris21_F_vs_WT_F.deseq.csv",  header = TRUE)[1:6]
colnames(df6)[3:6] = paste('6', colnames(df6)[3:6], sep='.')

df7 = read.csv("../1.deseq_csv/7.type_WT_F_vs_WT.deseq.csv",  header = TRUE)[1:6]
colnames(df7)[3:6] = paste('7', colnames(df7)[3:6], sep='.')

df8 = read.csv("../1.deseq_csv/8.Tris13_F_vs_Tris13.deseq.csv",  header = TRUE)[1:6]
colnames(df8)[3:6] = paste('8', colnames(df8)[3:6], sep='.')

df9 = read.csv("../1.deseq_csv/9.Tris18_F_vs_Tris18.deseq.csv",  header = TRUE)[1:6]
colnames(df9)[3:6] = paste('9', colnames(df9)[3:6], sep='.')

df10 = read.csv("../1.deseq_csv/10.Tris21_F_vs_Tris21.deseq.csv",  header = TRUE)[1:6]
colnames(df10)[3:6] = paste('10', colnames(df10)[3:6], sep='.')

## exp normed
df_normed = read.csv("../1.deseq_csv/1.Tris13_vs_WT.deseq.csv", header = TRUE)
df_normed <- df_normed[,c(1, 7:ncol(df_normed))]
colnames(df_normed)[2:ncol(df_normed)] = 
    paste(colnames(df_normed)[3:14], "DESeq2_Normed", sep='.')
df_normed <- df_normed[,c(1, 7:ncol(df_normed))]

## Annotation
df_anno <- read.csv("../3.annotation/anno.csv", header = TRUE)


## Location
df_location <- read.table("../../featureCount/counts.gene_id.txt", 
                        sep="\t", header=TRUE)[1:6]
colnames(df_location)[1] = "Gene"
df_location$Chr <- gsub("\\;.+$", "", df_location$Chr)  # remove duplicated parts
df_location$Strand <- gsub("\\;.+$", "", df_location$Strand)  # remove duplicated parts
df_location$Start <- gsub("\\;.+$", "", df_location$Start)  # remove duplicated parts
df_location$End <- gsub("^.+\\;", "", df_location$End)  # remove duplicated parts


colnames(df1)
colnames(df_normed)
colnames(df_anno)
colnames(df_location)

```

## merge stats
```{r}
df_stats <- Reduce( function(x, y) 
                    merge(x, y, by=c('Gene', "baseMean"), all=TRUE), 
                    list(
                         df1, df2, df3,df4,df5,df6,df7, df8, df9, df10
                         ))

colnames(df_stats)
```

## Merge Anno
```{r}
df_anno <- merge(df_anno, df_location, by="Gene", all=T)
colnames(df_anno)

df_merged <-merge(df_anno, df_stats, by="Gene", all=F)
colnames(df_merged)
dim (df_merged)
dim(df_stats)
```

```{r}
write.csv(df_merged, 'merged.csv', row.names = FALSE)
# library(xlsx)
# write.xlsx(df_merged, "merged.xlsx")

library(WriteXLS)
WriteXLS(x = df_merged, 
         ExcelFileName = 'merged.xlsx', row.names = F, SheetNames = 'sheet1', na = '-')

```