# Analysis Params
SAMPLES:
    - S1
    - S2

PAIR_END: False  # True/False

GENOME:
    genome/test.fa
INDEX:
    genome/star_idx
GTF:
    genome/test.gtf
ANNO_TAB:
  ~/github/bpipes/rnaseq/annotations/gencode.hu.v29/gencode.v29.primary_assembly.anno.txt.gz

STRAND: [0, 1, 2]  # can run [0, 1, 2] to get all possible results, can also select one

# script paths
FPKM: "scripts/rnaseq_normalization_annotation.R"
