# Analysis Params
SAMPLES:
    - A
    - B

PAIR_END: True  # True/False

GENOME:
    genome/Saccharomyces_cerevisiae.R64-1-1.dna.toplevel.fa
INDEX:
    genome/star_idx
GTF:
    genome/Saccharomyces_cerevisiae.R64-1-1.90.gtf
ANNO_TAB:
    ../../rnaseq/annotations/yeast.R64-1-1.90/Saccharomyces_cerevisiae.R64-1-1.90.anno.txt.gz

STRAND: [0, 1, 2]  # can run [0, 1, 2] to get all possible results, can also select one
MODE: ["liberal", "strict"] # liberal: Multi-Mapping, No fragment size reqirement; strict: opposite
