configfile: "config.yaml"
PAIR_END=config["PAIR_END"]
SAMPLE_INFO=config["SAMPLE_INFO"]


# Read sample info (solved)
import pandas as pd
df = pd.read_csv(SAMPLE_INFO,  comment='#')
SAMPLES=list(df.iloc[:, 0])
R1=list(df.iloc[:, 1])

if PAIR_END:
    R2=list(df.iloc[:, 2])
    Reads=list(zip(R1, R2))
    Reads=[" ".join(x) for x in Reads]
else:
    Reads=R1

print("samples.csv:\n", df)
print("PAIR_END: ", PAIR_END)
print("SAMPLES: ", SAMPLES)
print("Reads:"); print("\n".join(Reads))


# Feeding sample info (fail)
rule all:
    params:
        feed_read=expand("{read}.txt", read=Reads),
        feed_sample=expand("{sample}.txt", sample=SAMPLES),
        feed_r1=expand("{r1}.txt", r1=R1),
        feed_r2=expand("{r2}.txt", r2=R2),

rule map:
    input:
        r1={wildcards.r1},
        r2={wildcards.r2}
    output:
        {sample}.bam
    shell:
        "echo {input.r1} {input.r2} > {output}"

