# Analysis Params
DATA_TYPE: ChIP  # ChIP, DamID, ATAC
MODE: PE  # PE, MACS2 PE mode; SITE, get GATC site, macs2 damid mode; SE, single end (todo)
# todo: merge, ChIP, DamID-PE, DamID-SITE, ATAC-SITE
ALIGNER: bwa # bowtie2, bwa (default)

SAMPLES:
    - sample1
    - sample2
    - input1 
    - input2


GENOME: /project/umw_mccb/genome/Mus_musculus_UCSC_mm10/mm10.ucsc.fa
GTF: /project/umw_mccb/genome/Mus_musculus_UCSC_mm10/gencode.vM25.primary_assembly.annotation.gtf
BLACKLIST: /project/umw_mccb/genome/Blacklist/lists/mm10-blacklist.v2.bed
GSIZE: "mm"  # MACS2 gsize param, hs, mm, ce, dm, 2.7e8
SizeFile: /project/umw_mccb/genome/Mus_musculus_UCSC_mm10/star_idx/chrNameLength.txt # for bedGraphToBigWig, and hmmratac

BIN_SIZE: 2000 # For plotFingerprint, multiBamSummary, 2000 for mouse ATAC-seq
MQ_MIN: 20 # multiBamSummary, plotFingerprint

# Filters for bamCoverage, plotFingerprint, multiBamSummary
BW_BIN_SIZE: 20
minFragmentLength: 50  # 100 for mono-nucleosome
maxFragmentLength: 1000 # 200 for mono-nucleosome ATACseq fragments
signalHeatmapWidth: 3000 # upsteam/downstream of TSS/PeakCenter for plotHeatmap


# Peak caller
PEAKCALLER: narrow # narrow, broad, not implemented yet

# ChIPPeakAnno related
BIDING_LEFT: 3000
BIDING_RIGHT: 3000 # flanking TSS, for TSS ajacency peak count histogram
CHIPPEAKANNO_MODE: overlapping  # overlapping, both (overlapping and nearestLocation), just use overlapping, both mode buggy

# DB related
MIN_LFC: 0
MAX_FDR: 0.05


# MEME related
MEME_DB: /project/umw_mccb/genome/Mus_musculus_UCSC_mm10/motifs/hocomoco/HOCOMOCOv11_full_MOUSE_mono_meme_format.meme
PEAK_WIDTH: # center in peak summit
    - 1000
    - 2000
CHRS:
    - chr1
    - chr2
    - chrM
    - chrX
    - chrY
