from snakemake.utils import min_version
min_version("6.0")

configfile: 'config/config.yaml'
SAMPLES=config['SAMPLES']

from modules import parse_meta_contrast, get_treatment_bams_from_contrast, \
    get_control_bams_from_contrast, get_contrast_name_from_contrast, \
    get_treat_pileup_bdg_names_from_contrasts, get_treat_pileup_bw_names_from_contrasts, \
    get_control_lambda_bw_names_from_contrasts, get_meme_split_outname_from_contrasts, get_meme_outname_from_contrasts

o=parse_meta_contrast(fmeta="config/meta.csv", fcontrast="config/contrast.csv") 

rule main_targets:
    input:
        # qc
        fastqc="results/fastqc/multiqc_report.html", # not in main workflow, so list here
        multiqc_sorted_reads="results/sorted_reads_qc/multiqc_report.html",
        multiqc_clean_reads="results/clean_reads_qc/multiqc_report.html",
        chipqc1="results/clean_reads_qc/fingerprint.pdf",
        chipqc2="results/clean_reads_qc/fragment_size.pdf", # test 
        chipqc3="results/clean_reads_qc/multiBamSummary.heatmap.pdf",
        chipqc4="results/clean_reads_qc/multiBamSummary.pca.pdf",
        #chipqc5=expand("results/clean_reads_qc/{sample}.insert_size.pdf", sample=SAMPLES), # Rscript env problem
        chipqc5=expand("results/clean_reads_qc/insert_size/{sample}.insert_size.pdf", sample=SAMPLES),

        # call peak and create signal tracks
        # narrow peak
        macs2_sample_level_peaks=expand("results/macs2_sample_level_peaks/{sample}_peaks.narrowPeak", sample=SAMPLES),
        macs2_sample_treat_pileup_bw=expand("results/macs2_sample_level_peaks/{sample}_treat_pileup.bw", sample=SAMPLES),
        macs2_contrast_level_peaks=get_treat_pileup_bdg_names_from_contrasts(contrasts=o.contrasts, o=o), 
        macs2_contrast_treat_pileup_bw=get_treat_pileup_bw_names_from_contrasts(contrasts=o.contrasts, o=o),
        macs2_contrast_control_lambda_bw=get_control_lambda_bw_names_from_contrasts(contrasts=o.contrasts, o=o),
        macs2_narrow_peak_count = expand("results/macs2_sample_level_peaks/{sample}.count.txt", sample=SAMPLES),

        # motifs
        meme=get_meme_outname_from_contrasts(contrasts=o.contrasts, PEAK_WIDTH=config['PEAK_WIDTH'], o=o),
        #meme_split=get_meme_split_outname_from_contrasts(contrasts=o.contrasts, PEAK_WIDTH=config['PEAK_WIDTH'], CHRS=config['CHRS'], o=o),
        # Learn: Good trick to use tagets input to do contrast2contrast_name and more



        dag="Workflow_DAG.svg"

include: 'rules/fastqc.smk'
include: 'rules/chipmapping.smk'
include: 'rules/chipbamfilter.smk'
include: 'rules/bamqc.smk'
include: 'rules/chipqc.smk'
include: 'rules/Snakefile_DamID.smk'
include: 'rules/snakemake_misc.smk'
