# Analysis Params
SAMPLES:
    Epi_EED_Rep1
    Epi_Input_Rep1
    Epi_K27me3_Rep1
    Mes_EED_Rep1
    Mes_Input_Rep1
    Mes_K27me3_Rep1

GENOME: /project/umw_mccb/genome/Homo_sapiens/ucsc_hg38_primary/hg38.primary.fa
GTF: /project/umw_mccb/genome/Homo_sapiens/ucsc_hg38_primary/gencode.v29.primary_assembly.annotation.fixed.gtf


BIN_SIZE: 500 # For plotFingerprint, multiBamSummary 
MQ_MIN: 0 # multiBamSummary, plotFingerprint

# Filters for bamCoverage, plotFingerprint, multiBamSummary
minFragmentLength: 50  # 100 for mono-nucleosome
maxFragmentLength: 1000 # 200 for mono-nucleosome ATACseq fragments



