# Analysis Params
SAMPLES:
    - A
    - B

GENOME:
    genome/test.fa
    #/project/umw_mccb/genome/Homo_sapiens/ucsc_hg38_primary/hg38.primary.fa

GTF:
    /project/umw_mccb/genome/Homo_sapiens/ucsc_hg38_primary/gencode.v29.primary_assembly.annotation.fixed.gtf

MQ_MIN:
    0
