---
title: "Venn:"
author: "RuiLi"
date: "05/24/2019"
output:
  html_document:
    toc: yes  # table of content
    code_folding: hide
    toc_float: yes
---

```{r setup, include=FALSE}
library(VennDiagram)
library(gdata)
library(WriteXLS)
MIN_LFC <- 1
MIN_FDR <- 0.05

filter_sig_genes <- function(df, MIN_FDR, MIN_LFC){
    largeLFC <- abs(df$logFC) > MIN_LFC 
    smallFDR <- df$FDR < MIN_FDR
    sig_idx <- largeLFC & smallFDR
    print(table(largeLFC))
    print(table(smallFDR))
    print(table(sig_idx))
    
    return (df[sig_idx,])
}
```

## Notes:
- Goal: Mutation specific stress effect
1. 


## Read C11 (Stress: ZIP3 vs WT)
```{r readdata}
name1 <- "C11" # c11.gk3164_spg7.VS.wt_spg7
df1 <- readxl::read_xlsx( '../20171109.batch1.edgeR.results.with.CPM-2.xlsx', na='-', sheet=11)  # na term important
df1 <- data.frame(df1)  #important

colnames(df1)
dim(df1)



df1_sig <- filter_sig_genes(df1, MIN_FDR, MIN_LFC)
head(df1_sig)


list1 <- df1_sig$Row.names
area1 <- length(list1)
```


## Read C10: (Stress: ATFS-1 vs WT) 
```{r}
name2 <- "C10" # c10.tm4919_spg7.VS.wt_spg7
df2 <- readxl::read_xlsx( '../20171109.batch1.edgeR.results.with.CPM-2.xlsx', na='-', sheet=10)  # na term important
df2 <- data.frame(df2)  #important

colnames(df2)
dim(df2)



df2_sig <- filter_sig_genes(df2, MIN_FDR, MIN_LFC)
head(df2_sig)


list2 <- df2_sig$Row.names
area2 <- length(list2)
```

## Overlap
```{r}
overlap <- intersect(list1, list2)
overlap_area <- length(overlap)
```

## Venn plot
```{r}
pdf("venn.pdf")
## A more complicated diagram Demonstrating external area labels
venn.plot <- draw.pairwise.venn(area1           = area1,
                                area2           = area2,
                                cross.area      = overlap_area,
                                category        = c(name1, name2),
                                fill            = c("blue", "red"),
                                lty             = c("solid", 'solid'),
                                scaled = F,
                                alpha = 0.5,
                                cex             = 2,  # size of label
                                cat.cex         = 2,  # size of category names
                                cat.pos         = c(0, 0),
                                cat.dist        = 0.03,
                                # cat.just        = list(c(0, 0), c(0.5, 0)),
                                # ext.pos         = 0,
                                # ext.dist        = -0.05,
                                # ext.length      = 0.85,
                                # ext.line.lwd    = 2,
                                # ext.line.lty    = "dashed"
                               )
dev.off()
```
# Save Gene List
## df1 specific
```{r}
df1_specific <- data.frame(X=setdiff(list1, list2))
df1_specific <- merge(df1, df1_specific, by.x = 1, by.y = 1)

WriteXLS(x = df1_specific, 
         ExcelFileName = paste(name1, "specific", 'xlsx', sep = '.'), 
         row.names = F, SheetNames = 'sheet1', na = '-')
```

## df2 specific
```{r}
df2_specific <- data.frame(X=setdiff(list2, list1))
df2_specific <- merge(df2, df2_specific, by.x = 1, by.y = 1)

WriteXLS(x = df2_specific, 
         ExcelFileName = paste(name2, "specific", 'xlsx', sep = '.'), 
         row.names = F, SheetNames = 'sheet1', na = '-')
```


## Overlap in df1
```{r}
df_overlap1 <- data.frame(X=intersect(list2, list1))
df_overlap1 <- merge(df1, df_overlap1, by.x = 1, by.y = 1)

WriteXLS(x = df_overlap1, 
         ExcelFileName = paste("overlap", name1, 'xlsx', sep = '.'), 
         row.names = F, SheetNames = 'sheet1', na = '-')
```



## Overlap in df2
```{r}
df_overlap2 <- data.frame(X=intersect(list2, list1))
df_overlap2 <- merge(df2, df_overlap2, by.x = 1, by.y = 1)

WriteXLS(x = df_overlap2, 
         ExcelFileName = paste("overlap", name2, 'xlsx', sep = '.'), 
         row.names = F, SheetNames = 'sheet1', na = '-')
```

