---
title: "Venn 4Groups (Plot Only, No list)"
author: "RuiLi"
date: "06/05/2019"
output:
  html_document:
    toc: yes  # table of content
    code_folding: hide
    toc_float: yes
---

```{r setup, include=FALSE}
library(VennDiagram)
library(gdata)
library(WriteXLS)
MIN_LFC <- 0
MIN_FDR <- 0.05

name <- paste("Three", "FDR", MIN_FDR, "LFC", MIN_LFC, sep = ".")

name1 <- "T13_vs_WT"
name2 <- "T18_vs_WT"
name3 <- "T21_vs_WT"

filter_sig_genes <- function(df, MIN_FDR, MIN_LFC){
    df <- df[!is.na(df$padj), ]
    largeLFC <- abs(df$log2FoldChange_shrinked) > MIN_LFC 
    smallFDR <- df$padj < MIN_FDR
    sig_idx <- largeLFC & smallFDR
    print(table(largeLFC))
    print(table(smallFDR))
    print(table(sig_idx))
    
    return (df[sig_idx,])
}
```

## Code Notes:
- Venn of 4 Groups or 3 groups
- Plot Only, No list output
- output merged df of 1,2,3
- output overlapp of 1,2,3, after renaming lfc to lfc_name1,2,3
- change row.names to Name + Chr


## Read A
```{r readdata}
df1 <- readxl::read_xlsx( '../DESeq2/T13_vs_WT.deseq2.xlsx', na='-', sheet=1)  # na term important
df1 <- data.frame(df1)  #important

colnames(df1)
dim(df1)



df1_sig <- filter_sig_genes(df1, MIN_FDR, MIN_LFC)
head(df1_sig)


list1 <- df1_sig$Row.names
area1 <- length(list1)
```


## Read B
```{r}
df2 <- readxl::read_xlsx( '../DESeq2/T18_vs_WT.deseq2.xlsx', na='-', sheet=1)  # na term important
df2 <- data.frame(df2)  #important

colnames(df2)
dim(df2)

df2_sig <- filter_sig_genes(df2, MIN_FDR, MIN_LFC)
head(df2_sig)


list2 <- df2_sig$Row.names
area2 <- length(list2)
```

## Read C
```{r}
df3 <- readxl::read_xlsx( '../DESeq2/T21_vs_WT.deseq2.xlsx', na='-', sheet=1)  # na term important
df3 <- data.frame(df3)  #important

colnames(df3)
dim(df3)

df3_sig <- filter_sig_genes(df3, MIN_FDR, MIN_LFC)
head(df3_sig)


list3 <- df3_sig$Row.names
area3 <- length(list3)
```

<!-- ## Read D -->
<!-- ```{r} -->
<!-- name4 <- "D" # c10.tm4919_spg7.VS.wt_spg7 -->
<!-- df4 <- readxl::read_xlsx( '../D_20_vs_0.deseq2.sig.FDR.0.05.LFC.1.xlsx', na='-', sheet=1)  # na term important -->
<!-- df4 <- data.frame(df4)  #important -->

<!-- colnames(df4) -->
<!-- dim(df4) -->

<!-- df4_sig <- filter_sig_genes(df4, MIN_FDR, MIN_LFC) -->
<!-- head(df4_sig) -->


<!-- list4 <- df4_sig$Row.names -->
<!-- area4 <- length(list4) -->
<!-- ``` -->


## Venn
```{r}
venn.diagram(
    x = list(df1_sig$Gene , 
             df2_sig$Gene , 
             df3_sig$Gene
             #, df4_sig$Gene
             ),
    category.names = c(name1 , name2, name3
                       #, name4
                       ),
    filename = paste(name,'venn.png', sep = "."),
    fill = c('yellow', 'blue', 'orange'
             #, 'purple'
             ),
    main = name
)
```

# Save Gene List

## Merge df123
```{r}
## merge stats
colnames(df1)[9:15] <- paste(colnames(df1)[9:15], name1, sep = "_")
colnames(df2)[9:15] <- paste(colnames(df2)[9:15], name2, sep = "_")
colnames(df3)[9:15] <- paste(colnames(df3)[9:15], name3, sep = "_")

df123 <- Reduce(function(x,y) merge(x,y, by=colnames(df1)[c(1:8, 16:32)], all=T),
                list(df1, df2, df3))

# WriteXLS(x = df123, 
#          ExcelFileName = paste("three.merged.deseq2", 'xlsx', sep = '.'), 
#          row.names = F, SheetNames = 'sheet1', na = '-')

colnames(df123)
```

## Overlap
```{r}
overlap_12 <- data.frame(X=intersect(df1_sig$Name, df2_sig$Name))
overlap_23 <-  data.frame(X=intersect(df2_sig$Name, df3_sig$Name))
overlap_13 <- data.frame(X=intersect(df1_sig$Name, df3_sig$Name))
overlap_123 <- Reduce(intersect, list(df1_sig$Name, df2_sig$Name, df3_sig$Name))

df_overlap123 <- subset(df123, Name %in% overlap_123)

WriteXLS(x = df_overlap123, 
         ExcelFileName = paste(name, 'xlsx', sep = '.'), 
         row.names = F, SheetNames = 'sheet1', na = '-')
```

