---
title: "Heatmap for DEG: Tom and Nathan, 3 sets of DE Sig Genes"
author: "RuiLi"
date: "8/30/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("pheatmap")
```

# Read Data
```{r}
require(gdata)  #best
df = read.xls ("../merged.deseq.ann.rui.xls", sheet = 1, header = TRUE)

row.names(df) <- df[,1]
df <- df[, -1]
colnames(df)

thr_p <- 0.05
thr_lfc <- 1

# select expression columns
df_ <- df[, c(1:8, 15, 10)]
colnames(df_)

# remove NA from padj
sum(is.na(df$padj.WT.TRT.UNT))
df[is.na(df$padj.WT.TRT.UNT), 'padj.WT.TRT.UNT'] <- 1  
sum(is.na(df$padj.WT.TRT.UNT))

sum(is.na(df$padj.MUT.TRT.UNT))
df[is.na(df$padj.MUT.TRT.UNT), 'padj.MUT.TRT.UNT'] <- 1  
sum(is.na(df$padj.MUT.TRT.UNT))

sum(is.na(df$log2FoldChange.WT.TRT.UNT))
df[is.na(df$log2FoldChange.WT.TRT.UNT), 'log2FoldChange.WT.TRT.UNT'] <- 0
sum(is.na(df$log2FoldChange.WT.TRT.UNT))

sum(is.na(df$log2FoldChange.MUT.TRT.UNT))
df[is.na(df$log2FoldChange.MUT.TRT.UNT), 'log2FoldChange.MUT.TRT.UNT'] <- 0 
sum(is.na(df$log2FoldChange.MUT.TRT.UNT))

# select significant genes
small_p_1 <- df$padj.WT.TRT.UNT<thr_p
small_p_2 <- df$padj.MUT.TRT.UNT<thr_p

large_lfc1 <- abs(df$log2FoldChange.WT.TRT.UNT) > thr_lfc
large_lfc2 <- abs(df$log2FoldChange.MUT.TRT.UNT) > thr_lfc

df_sig1 <- df_[small_p_1 | small_p_2, ]
df_sig_full1 <- df[small_p_1 | small_p_2, ]
num_sig1 <- dim(df_sig1)[1]
paste(num_sig1)

df_sig2 <- df_[(small_p_1 & large_lfc1) | (small_p_2 & large_lfc2), ]
df_sig_full2 <- df[(small_p_1 & large_lfc1) | (small_p_2 & large_lfc2), ]
num_sig2 <- dim(df_sig2)[1]
paste(num_sig2)
```


## Heatmap for DEG of all Comparisons, clustered on all 8 samples from WT and MUT, small_fdr < 0.05 and large_lfc > 1
```{r, echo=FALSE}
name <- 'All Genotype: TRT vs UNT'
df_sig <- df_sig2
df_sig_full <- df_sig_full2
num_sig <- num_sig2

logNormed_sig <- log10(df_sig + 1)  # log transformation
head(logNormed_sig)

drows <- dist(logNormed_sig[, 1:8])

annotation_col <- data.frame(
                    genotype = factor(c(rep(c("MUT", "WT"), each=4), c("MUT", "WT"))),
                    treatment = factor(c(rep(c("TRT", "UNT", "TRT", "UNT"), each=2), rep("N.A.", 2))),
                    data = factor(c(rep("Expression", 8), rep("LFC(TRT/UNT)", 2)))
                            )

annotation_row <- data.frame(
  'WT' = factor(df_sig_full$padj.WT.TRT.UNT<thr_p),
  'MUT' = factor(df_sig_full$padj.MUT.TRT.UNT<thr_p)
)
rownames(annotation_row) = rownames(df_sig_full)

ann_colors = list(
    'WT' = c('TRUE'='red', 'FALSE'='gray'),
    "MUT" = c('TRUE'='black', 'FALSE'='gray')
)

rownames(annotation_col) <- colnames(logNormed_sig)

pheatmap(logNormed_sig, 
         cluster_rows=T, show_rownames=F,
         cluster_cols=F, show_colnames=F, 
         annotation_col = annotation_col,
         annotation_row = annotation_row, annotation_names_row = F,
         annotation_colors = ann_colors,
         clustering_distance_rows = drows,
         main = paste("Heatmap of", num_sig, " DEG for", name)
         )
```

## Heatmap for DEG of all Comparisons, clustered on all 8 samples from WT and MUT, small_fdr < 0.05 

```{r, echo=FALSE}
name <- 'All Genotype: TRT vs UNT'
df_sig <- df_sig1
df_sig_full <- df_sig_full1
num_sig <- num_sig1

logNormed_sig <- log10(df_sig + 1)  # log transformation
head(logNormed_sig)

drows <- dist(logNormed_sig[, 1:8])

annotation_col <- data.frame(
                    genotype = factor(c(rep(c("MUT", "WT"), each=4), c("MUT", "WT"))),
                    treatment = factor(c(rep(c("TRT", "UNT", "TRT", "UNT"), each=2), rep("N.A.", 2))),
                    data = factor(c(rep("Expression", 8), rep("LFC(TRT/UNT)", 2)))
                            )

annotation_row <- data.frame(
  'WT' = factor(df_sig_full$padj.WT.TRT.UNT<thr_p),
  'MUT' = factor(df_sig_full$padj.MUT.TRT.UNT<thr_p)
)
rownames(annotation_row) = rownames(df_sig_full)

ann_colors = list(
    'WT' = c('TRUE'='red', 'FALSE'='gray'),
    "MUT" = c('TRUE'='black', 'FALSE'='gray')
)

rownames(annotation_col) <- colnames(logNormed_sig)

pheatmap(logNormed_sig, 
         cluster_rows=T, show_rownames=F,
         cluster_cols=F, show_colnames=F, 
         annotation_col = annotation_col,
         annotation_row = annotation_row, annotation_names_row = F,
         annotation_colors = ann_colors,
         clustering_distance_rows = drows,
         main = paste("Heatmap of", num_sig, " DEG for", name)
         )
```

